window.ROME_DEFAULTS = {version:3, day:1, visited:[], places:[
{id:'colosseum',day:1,name:'Koloseum',category:'Antyczny Rzym',minutes:90,address:'Piazza del Colosseo, Roma',summary:'Wejdź w świat gladiatorów i poznaj niezwykłą machinę rzymskich widowisk.',history:'Stań na chwilę przed arkadami i wyobraź sobie tłum, który napływa tu z całego Rzymu. Amfiteatr Flawiuszów powstał w I wieku naszej ery z inicjatywy cesarzy tej dynastii. Na arenie odbywały się walki gladiatorów oraz polowania na dzikie zwierzęta. Za widowiskiem stała jednak także imponująca organizacja: przejścia, schody i zaplecze pozwalały obsłużyć ogromną publiczność.\n\nPrzez stulecia budynek zmieniał role. W średniowieczu mieścił warsztaty i mieszkania, a jego kamienie wykorzystywano jako materiał budowlany. Dzisiejsza ruina opowiada więc również o życiu miasta po upadku cesarstwa.',curiosity:'Nazwa „Koloseum” wiąże się z olbrzymim posągiem, który stał w pobliżu. Sama budowla była pierwotnie znana jako amfiteatr Flawiuszów.',look:'Przyjrzyj się rytmowi arkad i korytarzom pod dawną areną. Pomyśl o ludziach oraz mechanizmach ukrytych za spektaklem. Z zewnętrznych arkad poszukaj widoków na okolicę.',official:'https://colosseo.it/en/area/the-colosseum/',image:'',credit:''},
{id:'forum',day:1,name:'Forum Romanum',category:'Serce dawnego imperium',minutes:120,address:'Largo della Salara Vecchia 5/6, Roma',summary:'Świątynie, łuki i Via Sacra. Tutaj przez wieki toczyło się publiczne życie Rzymu.',history:'Dziś spacerujesz między ruinami, ale spróbuj usłyszeć gwar rozmów, spory polityków i kroki ludzi załatwiających codzienne sprawy. Ta dolina była niegdyś podmokła. Po jej osuszeniu, pod koniec VII wieku przed naszą erą, zaczęło kształtować się Forum. Przez ponad tysiąc lat pozostawało centrum życia publicznego.\n\nNie wszystko powstało jednocześnie: obok świątyń i budynków politycznych pojawiały się bazyliki służące sprawom sądowym oraz pomniki kolejnych władców. To zapis wielu pokoleń, a nie projekt jednego cesarza.',curiosity:'Po starożytności teren stopniowo zarastał i był znany jako Campo Vaccino, czyli pastwisko dla bydła. Część dawnych budowli przetrwała dzięki przekształceniu w kościoły.',look:'Nie próbuj zapamiętać każdej kolumny. Wybierz kilka punktów: łuk Septymiusza Sewera, świątynię Antonina i Faustyny oraz drogę Via Sacra. Zestaw ich skalę z pozostałościami mniejszych zabudowań.',official:'https://colosseo.it/en/area/the-roman-forum/',image:'',credit:''}
]};
window.ROME_DEFAULTS.places.push(
{id:'spanish',day:2,name:'Schody Hiszpańskie',category:'Rzymskie place',minutes:30,address:'Piazza di Spagna, Roma',summary:'Kamienna scenografia miasta: od fontanny w kształcie łodzi po Trinità dei Monti.',history:'Zacznij u stóp schodów. Ich rozgałęziające się biegi wyglądają jak teatralna dekoracja, ale rozwiązują bardzo praktyczny problem: łączą plac z położonym wyżej kościołem Trinità dei Monti. Zaprojektował je Francesco De Sanctis w XVIII wieku.\n\nSpójrz, jak stopnie rozchodzą się, zakręcają i ponownie spotykają. Spacer zmienia perspektywę niemal co kilka kroków. To dobry moment, by obserwować nie tylko zabytek, ale też miasto, które wciąż porusza się wokół niego.',curiosity:'U podnóża zobaczysz Barcaccię, fontannę Pietra Berniniego. Przypomina nisko zanurzoną łódź; nazwa nawiązuje do jednostek używanych na Tybrze.',look:'Z placu porównaj łagodne linie fontanny z szerokimi biegami schodów. Jeśli wybierzesz wejście na górę, zatrzymaj się na widok w stronę Via dei Condotti. Przy trudnościach z poruszaniem się można podziwiać schody z dołu.',official:'https://www.turismoroma.it/en/places/spanish-steps',image:'',credit:''},
{id:'trevi',day:2,name:'Fontanna di Trevi',category:'Woda i barok',minutes:30,address:'Piazza di Trevi, Roma',summary:'Najpierw słyszysz wodę. Za chwilę wąska uliczka otwiera się na wielki barokowy spektakl.',history:'Podejdź niespiesznie od jednej z wąskich uliczek. Nagłe pojawienie się tak monumentalnej fontanny to część jej uroku. Projekt Nicoli Salviego, wybrany w XVIII wieku, połączył fasadę Palazzo Poli z wodą, skałami i rzeźbami w jedną scenę.\n\nTrevi jest zakończeniem akweduktu Acqua Vergine. Dzięki temu za dekoracją kryje się bardzo długa historia doprowadzania wody do miasta. Wyobraź sobie Rzym, w którym fontanna była nie tylko ozdobą, lecz widocznym znakiem ogromnej infrastruktury.',curiosity:'Rzut monetą bywa traktowany jako obietnica powrotu do Rzymu. To popularna tradycja i opowieść podróżników, nie historyczna gwarancja spełnienia życzenia.',look:'Poszukaj centralnej postaci Oceanusa, koni morskich i trytonów. Zwróć uwagę, jak kamienna skała przechodzi w architekturę pałacu. Aktualne zasady dostępu do strefy fontanny sprawdź na oficjalnej stronie.',official:'https://www.turismoroma.it/it/luoghi/fontana-di-trevi',image:'',credit:''},
{id:'pantheon',day:2,name:'Panteon',category:'Światło i geometria',minutes:45,address:'Piazza della Rotonda, Roma',summary:'Jedna kopuła, otwarte niebo i światło, które powoli przemierza wnętrze.',history:'Po przejściu przez portyk unieś wzrok. Otwarte oko kopuły, oculus, wpuszcza do wnętrza światło oraz deszcz. Ruch jasnej plamy sprawia, że budowla wydaje się zmieniać razem z porą dnia.\n\nObecny Panteon powstał za cesarza Hadriana w II wieku naszej ery, w miejscu wcześniejszej fundacji Agrypy. Napis nad wejściem nadal przywołuje Agrypę. W VII wieku budowlę przekształcono w kościół Santa Maria ad Martyres, co pomogło jej przetrwać, gdy wiele antycznych zabytków rozbierano.',curiosity:'Wysokość wnętrza jest niemal równa średnicy kopuły — obie mają nieco ponad 43 metry. Wyobraź sobie kulę wpisaną w tę przestrzeń: jej górna połowa podążałaby za kopułą.',look:'Obejrzyj kasetony, czyli zagłębienia kopuły, i kolorowe wzory posadzki. Poszukaj grobu Rafaela. Panteon pozostaje miejscem kultu, więc oglądaj go spokojnie, z szacunkiem dla modlących się.',official:'https://www.turismoroma.it/en/places/pantheon',image:'',credit:''},
{id:'navona',day:2,name:'Plac Navona',category:'Barok pod gołym niebem',minutes:45,address:'Piazza Navona, Roma',summary:'Długi plac, trzy fontanny i ślad starożytnego stadionu ukryty w kształcie miasta.',history:'Zamiast od razu podchodzić do fontanny, obejrzyj cały plac. Jego wydłużony kształt nie jest przypadkiem: zachowuje zarys stadionu Domicjana. Rzym potrafi przez stulecia zmieniać budynki, ale pamiętać ich dawny plan.\n\nNa tym antycznym podłożu rozwinęła się jedna z najbardziej widowiskowych przestrzeni barokowego miasta. Fontanny, pałace i kościół tworzą tu otwartą scenę. Przejdź od jednego końca placu do drugiego i zobacz, jak zmieniają się proporcje fasad.',curiosity:'Centralna Fontanna Czterech Rzek Berniniego przedstawia cztery wielkie rzeki: Nil, Ganges, Dunaj i Rio de la Plata. Każda postać jest elementem opowieści o znanym wówczas świecie.',look:'Poszukaj zwierząt i roślin w kamiennej skale centralnej fontanny. Obejdź ją dookoła: rzeźby nie mają jednej „właściwej” strony. Potem spójrz na fasadę kościoła Sant’Agnese in Agone.',official:'https://www.turismoroma.it/en/node/1516',image:'',credit:''},
{id:'peter',day:3,name:'Bazylika św. Piotra',category:'Watykan',minutes:120,address:'Piazza San Pietro, Città del Vaticano',summary:'Monumentalna przestrzeń, mistrzowskie rzeźby i historia budowy trwającej ponad wiek.',history:'Zanim wejdziesz do bazyliki, daj sobie chwilę na placu. Dopiero człowiek stojący obok kolumn pozwala naprawdę odczuć skalę tego miejsca. Obecną świątynię zaczęto budować w 1506 roku, zastępując starszą bazylikę z czasów Konstantyna. Budowę ukończono w 1626 roku.\n\nTo dzieło wielu pokoleń artystów i architektów. We wnętrzu monumentalność spotyka się z detalem: wielkie przestrzenie prowadzą wzrok ku ołtarzowi, a rzeźby zachęcają, by zwolnić. Nie musisz zobaczyć wszystkiego naraz — wybierz kilka dzieł i poświęć im uwagę.',curiosity:'Bazylika św. Piotra nie jest katedrą Rzymu. Siedzibą biskupa Rzymu jest bazylika św. Jana na Lateranie. Słowa „bazylika” i „katedra” oznaczają różne funkcje kościoła.',look:'Poszukaj Piety Michała Anioła i baldachimu Berniniego. Spójrz wysoko ku kopule, a później wróć wzrokiem do drobnych detali. Ten plan obejmuje bazylikę, bez Muzeów Watykańskich i wejścia na kopułę. Uwzględnij dodatkowy czas na kontrolę bezpieczeństwa.',official:'https://www.basilicasanpietro.va/en/san-pietro/the-basilica',image:'',credit:''},
{id:'trastevere',day:3,name:'Zatybrze',category:'Trastevere · powolny spacer',minutes:90,address:'Piazza di Santa Maria in Trastevere, Roma',summary:'Ciepłe fasady, małe uliczki i plac, na którym dobrze po prostu pobyć.',history:'Po monumentalnym Watykanie czas zmienić skalę. Zatybrze najlepiej poznawać powoli: skręcić w boczną ulicę, spojrzeć na stare drzwi, zauważyć światło na tynku. Nazwa dzielnicy pochodzi od łacińskiego trans Tiberim — „za Tybrem”, względem dawnego centrum miasta.\n\nZa przyjemną atmosferą kryje się bogata historia. W okolicy są renesansowa Villa Farnesina, dawne kościoły i pałace, ale ten spacer zaczynamy na Piazza di Santa Maria in Trastevere. To konkretny punkt spotkania, a dalej możesz pozwolić sobie na odrobinę błądzenia.',curiosity:'Na Zatybrzu codzienność sąsiaduje ze sztuką najwyższej klasy. Villa Farnesina kryje freski Rafaela i jego pracowni — osobny pomysł na dłuższy pobyt, poza tym krótkim spacerem.',look:'Na głównym placu obejrzyj fasadę bazyliki Santa Maria in Trastevere oraz fontannę. Potem przejdź spokojnie uliczkami w stronę Piazza Trilussa. Nawigacja prowadzi na plac Santa Maria, a nie do granicy całej dzielnicy.',official:'https://www.turismoroma.it/en/node/49974',image:'',credit:''}
);
const photoCredits={
colosseum:['Julian Lupyan','CC0','https://commons.wikimedia.org/wiki/File:Colosseum,_Rome.jpg','https://creativecommons.org/publicdomain/zero/1.0/'],
forum:['Adrian Pingstone (Arpingstone)','domena publiczna','https://commons.wikimedia.org/wiki/File:Roman.forum.%26.arch.of.septimius.rome.arp.jpg','https://commons.wikimedia.org/wiki/Commons:Public_domain'],
spanish:['2pi.pl','CC BY 3.0','https://commons.wikimedia.org/wiki/File:Spanish_steps_Rome_Italy.jpg','https://creativecommons.org/licenses/by/3.0/'],
trevi:['Kurt Kaiser','CC0','https://commons.wikimedia.org/wiki/File:The_Trevi_Fountain,_Rome.jpg','https://creativecommons.org/publicdomain/zero/1.0/'],
pantheon:['Meshari Alawfi','CC BY 4.0','https://commons.wikimedia.org/wiki/File:PantheonRome.jpg','https://creativecommons.org/licenses/by/4.0/'],
navona:['Francisco Anzola','CC BY 2.0','https://commons.wikimedia.org/wiki/File:Piazza_Navona_(27470000165).jpg','https://creativecommons.org/licenses/by/2.0/'],
peter:['Hannes Flo','CC BY 2.0','https://commons.wikimedia.org/wiki/File:St._Peter%27s_Basilica_(51188242904).jpg','https://creativecommons.org/licenses/by/2.0/'],
trastevere:['Rudolfo Kithera','CC0','https://commons.wikimedia.org/wiki/File:Stra%C3%9Fe_in_Trastevere_1.jpg','https://creativecommons.org/publicdomain/zero/1.0/']};
window.ROME_DEFAULTS.places.forEach(p=>{p.image='images/'+p.id+'.webp';p.credit=photoCredits[p.id].join(' | ')});
window.ROME_PHOTOS=photoCredits;
// Dzień 1: roboczy plan Watykanu i Zamku Świętego Anioła na 10.10.2026.
window.ROME_DEFAULTS.places = window.ROME_DEFAULTS.places.filter(p => !['colosseum', 'forum'].includes(p.id));
const stPeter = window.ROME_DEFAULTS.places.find(p => p.id === 'peter');
Object.assign(stPeter, {day:1, minutes:75, category:'Watykan · kontrola bezpieczeństwa', summary:'Plac św. Piotra i wnętrze bazyliki: najważniejsze miejsce drugiej części dnia.'});
window.ROME_DEFAULTS.places.unshift(
  {id:'vatican-museums',day:1,name:'Muzea Watykańskie i Kaplica Sykstyńska',category:'Watykan · wejście zależne od kolejki',minutes:210,address:'Viale Vaticano, 00165 Roma',summary:'Plan główny: sprawdzenie kolejki i próba zakupu biletu na miejscu. Kaplica Sykstyńska jest częścią trasy Muzeów.',history:'Muzea Watykańskie to rozległy zespół kolekcji papieskich. W czasie jednego przejścia spotykają się tu rzeźba antyczna, sale Rafaela, galerie arrasów i map, a także Kaplica Sykstyńska. To właśnie dlatego warto potraktować wizytę jako jedną długą trasę, nie jako kilka niezależnych punktów.\n\nW tym planie nie ma rezerwacji. Najpierw sprawdź sytuację przy wejściu na Viale Vaticano, a dopiero potem zdecyduj, czy realizujesz wariant główny.',curiosity:'Kaplica Sykstyńska nie ma osobnego wejścia ani osobnego biletu. Jest częścią wizyty w Muzeach Watykańskich.',look:'Jeśli wejdziesz, rozłóż siły na całą trasę. W Kaplicy Sykstyńskiej obserwuj sklepienie i ścianę ołtarzową, ale pamiętaj o zasadach zachowania obowiązujących na miejscu.',official:'https://tickets.museivaticani.va',image:'images/peter.webp',credit:'Zdjęcie użyte poglądowo: Hannes Flo | CC BY 2.0 | https://commons.wikimedia.org/wiki/File:St._Peter%27s_Basilica_(51188242904).jpg | https://creativecommons.org/licenses/by/2.0/'},
  {id:'st-peters-square',day:1,name:'Plac św. Piotra',category:'Watykan · przerwa i przejście',minutes:15,address:'Piazza San Pietro, Città del Vaticano',summary:'Punkt przejścia między Muzeami a Bazyliką oraz dobre miejsce na szybki obiad w okolicy.',history:'Plac św. Piotra jest wielką przestrzenią wejściową bazyliki. Kolumnada Berniniego prowadzi wzrok ku fasadzie i porządkuje ruch pielgrzymów oraz turystów. Po długiej wizycie w Muzeach to dobry moment, by zwolnić, napić się wody i sprawdzić dalszy plan.',curiosity:'Układ kolumnady sprawia, że z wybranych punktów placu rzędy kolumn nakładają się optycznie na siebie.',look:'Stań bliżej obelisku i obejrzyj plac jako całość. Dopiero potem przejdź do kolejki bezpieczeństwa przy Bazylice.',official:'https://www.basilicasanpietro.va/en/san-pietro/the-basilica',image:'images/peter.webp',credit:'Hannes Flo | CC BY 2.0 | https://commons.wikimedia.org/wiki/File:St._Peter%27s_Basilica_(51188242904).jpg | https://creativecommons.org/licenses/by/2.0/'},
  {id:'castel-santangelo',day:1,name:'Zamek Świętego Anioła',category:'Rzym nad Tybrem',minutes:105,address:'Lungotevere Castello, 50, Roma',summary:'Twierdza nad Tybrem z trasą przez kolejne poziomy budowli i widokami na miasto.',history:'Budowla zaczęła życie jako mauzoleum cesarza Hadriana. Z czasem zmieniała funkcje: była twierdzą, schronieniem papieży, więzieniem i koszarami. Te warstwy widać w jej architekturze — od masywnej podstawy po późniejsze wnętrza.\n\nDziś mieści Muzeum Narodowe. Zwiedzanie ma swój rytm: przejście przez kolejne poziomy prowadzi na tarasy, z których można spojrzeć na Tyber, kopułę Bazyliki i zabudowę miasta.',curiosity:'Nazwa zamku wiąże się z posągiem anioła na szczycie. Według tradycji anioł miał ukazać się papieżowi Grzegorzowi Wielkiemu podczas zarazy.',look:'Zwróć uwagę na różnicę między cylindrycznym rdzeniem mauzoleum a późniejszymi umocnieniami. Na koniec zostaw chwilę na widok z tarasu.',official:'https://direzionemuseiroma.cultura.gov.it/en/museo-nazionale-di-castel-santangelo/',image:'images/peter.webp',credit:'Zdjęcie użyte poglądowo: Hannes Flo | CC BY 2.0 | https://commons.wikimedia.org/wiki/File:St._Peter%27s_Basilica_(51188242904).jpg | https://creativecommons.org/licenses/by/2.0/'},
  {id:'ponte-santangelo',day:1,name:'Most Świętego Anioła i Tyber',category:'Spacer po zwiedzaniu',minutes:45,address:'Ponte Sant’Angelo, Roma',summary:'Spokojny spacer po wyjściu z Zamku, w stronę mostu i nabrzeża Tybru.',history:'Most prowadzący do Zamku przez wieki był jedną z ważnych dróg w stronę Watykanu. Dzisiejsza nazwa łączy go z pobliską twierdzą. Spacer pozwala po intensywnym dniu zobaczyć, jak Tyber spaja dwie strony miasta.',curiosity:'Anioły na moście są związane z barokową oprawą trasy pielgrzymiej prowadzącej ku Watykanowi.',look:'Przejdź most powoli i obejrzyj Zamek z obu stron. Najlepszy moment na decyzję o dalszym spacerze albo kolacji w Prati.',official:'https://direzionemuseiroma.cultura.gov.it/en/museo-nazionale-di-castel-santangelo/',image:'images/peter.webp',credit:'Zdjęcie użyte poglądowo: Hannes Flo | CC BY 2.0 | https://commons.wikimedia.org/wiki/File:St._Peter%27s_Basilica_(51188242904).jpg | https://creativecommons.org/licenses/by/2.0/'}
);
const dayOneOrder = ['vatican-museums', 'st-peters-square', 'peter', 'castel-santangelo', 'ponte-santangelo'];
const orderedDayOne = dayOneOrder.map(id => window.ROME_DEFAULTS.places.find(p => p.id === id)).filter(Boolean);
window.ROME_DEFAULTS.places = [...orderedDayOne, ...window.ROME_DEFAULTS.places.filter(p => !dayOneOrder.includes(p.id))];
